version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
      python: 3.9
  pre_build:
    commands:
      - echo installing dependencies...
      - pipenv install
      - npm install
  build:
    commands:
      - pipenv run python manage.py collectstatic --no-input
      - cd frontend
      - npm run build-with-static
artifacts:
  files:
    - "**/*"