version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8.x
  pre_build:
    commands:
      - echo installing dependencies...
      - cd frontend
      - npm install
  
artifacts:
  files:
    - "**/*"