version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      - npm run build-with-static
artifacts:
  files:
    - "**/*"