# Generated by Django 2.1.3 on 2018-11-10 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='markdown_text',
            field=models.TextField(default='*testMarkdown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='regions_visited',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=['Washington'], size=None),
            preserve_default=False,
        ),
    ]
