# Generated by Django 2.1 on 2018-12-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181216_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='markdown',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
