# Generated by Django 2.1 on 2018-12-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_journey_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='legs',
        ),
    ]
